import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pacifico.className} antialiased`}>{children}</body>
      <link rel="preload" as="image" href="/images/bg.png" />
      <link rel="preload" as="image" href="/images/envelope.png" />
    </html>
  );
}
